### PR TITLE
Update dominant_assurance_contract.md - Bob is $5000 poorer  i/o $500 richer

### PR DESCRIPTION
**Pull request by sjamayee**

### CODE REVIEW

**Comment by zack-bitcoin** [comment]
No, what you suggest is wrong.
It was correct, and you introduced an error.

If the bridge is not built, then he gets his $5000 back, plus 10% interest. so he is $500 richer than the start.

**Comment by sjamayee** [comment]
But, you started with this:
> For example, lets say Bob owns a store that will be $10,000 more valuable if a bridge gets built.

In some cases you take this into account and in this case you don't care.
I think that I will go back to school.

**Comment by zack-bitcoin** [comment]
Yes, you are right. The way I wrote it is confusing. This could be improved.

**Comment by zack-bitcoin** [comment]
ok, I rewrote some of it. Hopefully it makes more sense now.

**Pull request closed without merging**
