### PR TITLE
Teach CI to check code generated from Swagger

### PR DESCRIPTION
**Pull request by lucafavatella**
This is rebased version of PR #257. See https://github.com/aeternity/testnet/pull/257#issuecomment-319812007 for context.

### CODE REVIEW

**Comment by sennui** [comment]
still faililg (i didn't check logs)

**Comment by lucafavatella** [comment]
> still faililg (i didn't check logs)

@sennui It fails on the Python tests job. As this PR does not touch the tests or code, this seems an instance of unstable tests. I re-triggered CI by closing and opening.

**Comment by lucafavatella** [comment]
> @sennui It fails on the Python tests job. As this PR does not touch the tests or code, this seems an instance of unstable tests. I re-triggered CI by closing and opening.

This seems tracked as https://github.com/aeternity/testnet/issues/218

**Comment by sennui** [comment]
@lucafavatella yes, surly timing issues, but I cannot merge red PR (just in case its something else)

until we fix 218 please retrigger to have it green like now

**Pull request merged**
