### PR TITLE
Mining fix

### PR DESCRIPTION
**Pull request by cytadela8**
I fixed misspelled function call that prevented mining.
Also: we should look into easier access to logs.
It took me some time to realise there are some problems being reported in `_build/prod/rel/ae_core/log/crash.log`

### CODE REVIEW

**Comment by sennui** [comment]
thanks a lot for the fix! how we didn't catch that in tests? We definitely need to add a test case. I will check that on monday

**Comment by cytadela8** [comment]
@sennui Isn't it possible to use some script to change for all misspelled function calls, variable names, etc.?

**Comment by sennui** [comment]
we are going to add dializer spec that will catch all of that. Anyway, if it was possible with current test coverage - it means that its far too sparse and we need it in non-trivial cases.

**Comment by cytadela8** [comment]
Even when I just run dialyzer (I'm a noob, don't ask me how I have done it), it showed many problems.
For example:
```
api.erl:346: Call to missing or unexported function channel_team_close_tx:make/4
api.erl:355: Call to missing or unexported function channel_solo_close:make/6
api.erl:360: Call to missing or unexported function channel_timeout_tx:make/4
api.erl:365: Call to missing or unexported function channel_slash_tx:make/6
```

**Comment by sennui** [comment]
I am aware of many of those, we are in process of picking them up

**Comment by sennui** [comment]
thanks...

**Comment by cytadela8** [comment]
I looks like mining forks when you start from clean blockchain. I think this may be connected to having no tx-s in tests. But I don't understand the code enough to make some. I think we should have some transactions tests. Such tests would show the mining stops working then. I will try to learn more about the code and I may make some tests with transactions when I find time.

**Comment by cytadela8** [comment]
Fixed upstream

**Pull request closed without merging**
