### PR TITLE
repo refactoring pr

### PR DESCRIPTION
**Pull request by sennui**
PR to follow repo refactoring

At any point it should be operational and mergable

Initial batch, before rebar work

### CODE REVIEW

**Comment by zack-bitcoin** [comment]
I don't want to get rid of `update.sh` now, because the code is changing so fast and it seriously reduces the number of times the code breaks for people.
I am even considering having all the blocks deleted every time you restart the node.

Moving the files around like that breaks a few pointers. 
I can't test this pull request with the network because it is using an old version of the code.
So I will manually move the files around how you suggest.

**Comment by sennui** [comment]
OK, can you merge to master the latest code?

**Comment by zack-bitcoin** [comment]
I will in a moment, it seems like the blocks aren't pushing to the server right. I need to mine 2 blocks to find out.

**Comment by zack-bitcoin** [comment]
It turns out we did need to start inets in testnet_app.erl
Please don't do a pull requestion unless the tests pass and you can sync with the network.

**Comment by michalzajda** [comment]
Very unlikely. I run in console `applicaton:which_applications()` before and after my change (recompilation in between) and in both cases inets was running, which means my code in .app file was turning it on.

Maybe another commit which *removes* inets breaks something (because I don't see why we have it, when cowboy is in deps and there is no usage of inets in /src). Maybe you use some hearder or record from inets and its not available when I removed it completely.

**Pull request closed without merging**
