### PR TITLE
Plant partial specification of code style

### PR DESCRIPTION
**Pull request by lucafavatella**
Please refer to commit message for details. See also https://github.com/aeternity/MerkleTrie/commit/2d4a6eae4d23fd3ce1dbf1b923022916fe111a2b

----

As some developers may perform some refactoring, I propose a structured approach for applying code conventions. These [can be improved](http://editorconfig.org/) of course e.g. `trim_trailing_whitespace`, `insert_final_newline`.

### CODE REVIEW

**Comment by sennui** [comment]
why don't we go classic emacs?

**Comment by sennui** [comment]
Also lets do only spaces, no tabs

**Comment by lucafavatella** [comment]
> why don't we go classic emacs?

Global emacs configuration in the Developer's setup may lead to unintended e.g. indentation width to end up in the code. Explicating as most as reasonable in a project-specific config file (editorconfig i editor-agnostic, and is available for emacs as well) would prevent most of that.

> Also lets do only spaces, no tabs

Will integrate this and push new commit.

**Comment by lucafavatella** [comment]
>> Also lets do only spaces, no tabs
> 
> Will integrate this and push new commit.

@sennui Done. I tested that emacs with editorconfig package obeys it.

**Comment by sennui** [comment]
I am adding this as a way of documenting our code-style. Its up for further changes

**Comment by lucafavatella** [comment]
BTW emacs - as many editors - [has plugin](http://editorconfig.org/) for detecting and applying at least partially the editorconfig file.

**Pull request merged**
