### PR TITLE
Plant network serialization of block

### PR DESCRIPTION
**Pull request by lucafavatella**
Please refer to commit message for details.

Follows from https://github.com/aeternity/testnet/pull/279#pullrequestreview-54785605

### CODE REVIEW

**Comment by lucafavatella** [comment]
I will run the `tester` on a clean node as recommended by @sennui then I will remove the "WIP" tag from the title of the PR.

**Comment by lucafavatella** [comment]
> I will run the tester on a clean node as recommended by @sennui then I will remove the "WIP" tag from the title of the PR.

I ran tester - as in PR #294 - and it passed. I am removing the WIP tag from the title.

**Comment by cytadela8** [comment]
You missed serliazation in 'download_blocks:do_send_blocks'.

**Comment by sennui** [comment]
@lucafavatella it would be good to add test covering case mentioned by Arthur

**Comment by lucafavatella** [comment]
> You missed serliazation in download_blocks:do_send_blocks. Check to make sure it's everywhere where we send and receive blocks.

> @lucafavatella it would be good to add test covering case mentioned by Arthur

@cytadela8 @sennui I believe both comments are addressed in commit b90e575 that I added to this PR.

**Comment by cytadela8** [comment]
@sennui The tests that would catch that are actually in #297 I think. Maybe I should separate them. Part of my whole package of changes to synchronization stuff was better `test_fork.py`. I forgot about that when splitting the changes yesterday.

**Comment by lucafavatella** [comment]
@sennui Following chat this morning I understand not amendments or further testing required for this PR. Of course please let me know if you would prefer me to run further checks.

**Pull request merged**
