### PR TITLE
Download blocks in batches finally fixed (+Arch instructions)

### PR DESCRIPTION
**Pull request by cytadela8**
I managed to finally fixed the problems that were in #113.

To justify myself: I had to make many changes to sending blocks (pushing). The previous code had many problems and even after some fixes new problems arrived.

@zack-bitcoin the problems you had were probably due to my blocks being send too fast. (when pushing blocks) If we received a new block before processing the previous one we rejected it. Now pushing works.

### CODE REVIEW

**Comment by cytadela8** [comment]
I will fix the merge conflicts shortly (today).

**Comment by sennui** [comment]
I need to analyze a bit more the trader function to do it maybe a bit more iterative rather than recursive with this bounce in sender. Thanks I will work on it this week - we can chat on slack about the best approach!

**Comment by sennui** [comment]
what was broken before? can you add test case? (we have some that mine and in the test mode its quick)

**Comment by cytadela8** [comment]
@sennui:
I'm available on slack as cytadela8.
There were few problems with previous pushing of blocks:
- if our peer were on a fork more then one block deep we would reach genesis block while looking for the commonblock.
- there was a sanity check when reviving a block (send_block) that prevented receiving of a block if previous received haven't been analysed.

**Comment by cytadela8** [comment]
When trying to fix those I had some other problems emerge and had to make more changes to finally achieve current version.

**Comment by cytadela8** [comment]
Currently there is one problem.
`block_absorber` is asynchronous so we may try to download the same blocks from multiple peers.

**Comment by sennui** [comment]
yes, and without ranking mechanism we pick up from all peers... thats seems like a lot of overhead and noise. 

And these are all good points, I was thinking about redoing sync to iterative version by first finding out real common block (this one by one), then preparing list of blocks to get and get them in one batch. Need to read your solution to see where it is

**Comment by cytadela8** [comment]
@sennui one can store with each block not only hash of it's parent but also of block 2 back in history, 4 back, 8... This way one can find common in log(n) requests.

But I think we should go other way about this. We should add the mechanism of just downloading the headers. (that's already planed) Then just download headers in batches till we see a block that we have.

At the moment I'm doing something a little bit similar, but with full blocks. (download in batches till I find common, then send everything from my top to common and absorb received blocks)

**Comment by cytadela8** [comment]
I added checks to `test_fork.py` that show the previous problem. (the tests fail on master, but on after my changes)

**Comment by cytadela8** [comment]
Please tell me if you would like to have some other checks. I think fork checks are the best checks for sync function.

**Comment by zack-bitcoin** [comment]
Good work. I will review this code tomorrow.

**Comment by cytadela8** [comment]
This was moved to #227

**Pull request closed without merging**
