### PR TITLE
improve release handling

### PR DESCRIPTION
**Pull request by sennui**
split current app into two aps
move bunch of values to config files
create 3 configs for development release
move JS files to priv dir and adjust handlers accordingly
add dializer target
add test target
move shell scripts to scripts directory
remove scripts that are covered by make (start, start_test)
remove update.sh script
remove oracle directory - its created by rebar
move js files to priv/ - this way they travel with release
update code that goes to web, web_external (not sure about bets)

### CODE REVIEW

**Comment by sennui** [comment]
looking into conflicts...

**Comment by sennui** [comment]
@zack-bitcoin I added some makefile targets in README. We can test together.

**Comment by sennui** [comment]
@zack-bitcoin Also I just realized: after attaching to node (which runs now as unix daemon) you can run any commands as before in interactive mode. But when you push Ctrl-C to leave attached console the node goes down --- I will add an option later to keep the node up

**Comment by zack-bitcoin** [comment]
looks great. I am running tests on this code now.

**Comment by zack-bitcoin** [comment]
A couple important lines were removed from .gitignore.
We don't want to push /deps or /ebin to the github repository, right? That is a lot of data.

**Comment by zack-bitcoin** [comment]
It looks like both versions of rebar are being installed.

**Comment by zack-bitcoin** [comment]
including rebar3 with the repository is a good idea.

I tried turning it on, and it crashed.
zack:~/Hacking/sennui_testnet$ make compile
===> Verifying dependencies...
===> Compiling ae_api
===> Compiling ae_core
zack:~/Hacking/sennui_testnet$ make local-release-start
make: ./_build/local/rel/ae_core/bin/ae_core: Command not found
Makefile:34: recipe for target 'local-release-start' failed
make: *** [local-release-start] Error 127
zack:~/Hacking/sennui_testnet$

**Comment by sennui** [comment]
@zack-bitcoin do you have this file that he is complaining above? 

./_build/local/rel/ae_core/bin/ae_core ?

Maybe there is conflict between two versions of rebar (only one is included!)

**Comment by sennui** [comment]
@zack-bitcoin we don't want to push those. In rebar3 all of that (deps and compiled code) lives in _build so its OK to remove old deps and ebin from .gitignore.

Can you clone this branch to fresh dir? It will let you see which directories there are and which got removed (when switching branches git may not remove some of those)

**Comment by sennui** [comment]
@zack-bitcoin btw. we can do screen share to go through it (the build process and reber interaction). I know that another user from Slack had issues with rebar2 vs rebar3 conflict (@Zwilla)

**Pull request closed without merging**
